// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portal_Aluno.Infrastructure.Data.DbContexts;

#nullable disable

namespace Portal_Aluno.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224233533_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("Ra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Ra"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bairro");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("celular");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Foto")
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pais");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rua");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Ra")
                        .HasName("pk_alunos");

                    b.ToTable("alunos", (string)null);
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CargaHoraria")
                        .HasColumnType("integer")
                        .HasColumnName("carga_horaria");

                    b.Property<string>("Grau")
                        .HasColumnType("text")
                        .HasColumnName("grau");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_cursos");

                    b.ToTable("cursos", (string)null);
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.CursoDisciplina", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("integer")
                        .HasColumnName("disciplina_id");

                    b.Property<int?>("Semestre")
                        .HasColumnType("integer")
                        .HasColumnName("semestre");

                    b.HasKey("CursoId", "DisciplinaId")
                        .HasName("pk_curso_disciplina");

                    b.HasIndex("DisciplinaId")
                        .HasDatabaseName("ix_curso_disciplina_disciplina_id");

                    b.ToTable("curso_disciplina", (string)null);
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CargaHoraria")
                        .HasColumnType("integer")
                        .HasColumnName("carga_horaria");

                    b.Property<int?>("LimiteFaltas")
                        .HasColumnType("integer")
                        .HasColumnName("limite_faltas");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_disciplinas");

                    b.ToTable("disciplinas", (string)null);
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_matricula");

                    b.Property<string>("FormaIngresso")
                        .HasColumnType("text")
                        .HasColumnName("forma_ingresso");

                    b.Property<int>("Ra")
                        .HasColumnType("integer")
                        .HasColumnName("ra");

                    b.Property<int?>("Semestre")
                        .HasColumnType("integer")
                        .HasColumnName("semestre");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Turno")
                        .HasColumnType("text")
                        .HasColumnName("turno");

                    b.HasKey("Id")
                        .HasName("pk_matriculas");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("ix_matriculas_curso_id");

                    b.HasIndex("Ra")
                        .IsUnique()
                        .HasDatabaseName("ix_matriculas_ra");

                    b.ToTable("matriculas", (string)null);
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.MatriculaTurma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Faltas")
                        .HasColumnType("integer")
                        .HasColumnName("faltas");

                    b.Property<int>("MatriculaId")
                        .HasColumnType("integer")
                        .HasColumnName("matricula_id");

                    b.Property<decimal?>("Nota")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("nota");

                    b.Property<string>("Situacao")
                        .HasColumnType("text")
                        .HasColumnName("situacao");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer")
                        .HasColumnName("turma_id");

                    b.HasKey("Id")
                        .HasName("pk_matricula_turma");

                    b.HasIndex("MatriculaId")
                        .HasDatabaseName("ix_matricula_turma_matricula_id");

                    b.HasIndex("TurmaId")
                        .HasDatabaseName("ix_matricula_turma_turma_id");

                    b.ToTable("matricula_turma", (string)null);
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("Expiracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiracao");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Foto")
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_professores");

                    b.ToTable("professores", (string)null);
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Andar")
                        .HasColumnType("integer")
                        .HasColumnName("andar");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("pk_salas");

                    b.ToTable("salas", (string)null);
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<int?>("Capacidade")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<string>("DiaSemana")
                        .HasColumnType("text")
                        .HasColumnName("dia_semana");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("integer")
                        .HasColumnName("disciplina_id");

                    b.Property<TimeOnly?>("HoraAulaFim")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_aula_fim");

                    b.Property<TimeOnly?>("HoraAulaInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_aula_inicio");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer")
                        .HasColumnName("professor_id");

                    b.Property<int?>("SalaId")
                        .HasColumnType("integer")
                        .HasColumnName("sala_id");

                    b.Property<int?>("Semestre")
                        .HasColumnType("integer")
                        .HasColumnName("semestre");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Turno")
                        .HasColumnType("text")
                        .HasColumnName("turno");

                    b.HasKey("Id")
                        .HasName("pk_turmas");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("ix_turmas_curso_id");

                    b.HasIndex("DisciplinaId")
                        .HasDatabaseName("ix_turmas_disciplina_id");

                    b.HasIndex("ProfessorId")
                        .HasDatabaseName("ix_turmas_professor_id");

                    b.HasIndex("SalaId")
                        .HasDatabaseName("ix_turmas_sala_id");

                    b.ToTable("turmas", (string)null);
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("ReferenciaId")
                        .HasColumnType("text")
                        .HasColumnName("referencia_id");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_login");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.CursoDisciplina", b =>
                {
                    b.HasOne("Portal_Aluno.Domain.Entities.Curso", "Curso")
                        .WithMany("CursoDisciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_curso_disciplina_cursos_curso_id");

                    b.HasOne("Portal_Aluno.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany("CursoDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_curso_disciplina_disciplinas_disciplina_id");

                    b.Navigation("Curso");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Matricula", b =>
                {
                    b.HasOne("Portal_Aluno.Domain.Entities.Curso", "Curso")
                        .WithMany("Matriculas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matriculas_cursos_curso_id");

                    b.HasOne("Portal_Aluno.Domain.Entities.Aluno", "Aluno")
                        .WithOne("Matricula")
                        .HasForeignKey("Portal_Aluno.Domain.Entities.Matricula", "Ra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matriculas_alunos_ra");

                    b.Navigation("Aluno");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.MatriculaTurma", b =>
                {
                    b.HasOne("Portal_Aluno.Domain.Entities.Matricula", "Matricula")
                        .WithMany("MatriculaTurmas")
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matricula_turma_matriculas_matricula_id");

                    b.HasOne("Portal_Aluno.Domain.Entities.Turma", "Turma")
                        .WithMany("MatriculaTurmas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matricula_turma_turmas_turma_id");

                    b.Navigation("Matricula");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Turma", b =>
                {
                    b.HasOne("Portal_Aluno.Domain.Entities.Curso", "Curso")
                        .WithMany("Turmas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_turmas_cursos_curso_id");

                    b.HasOne("Portal_Aluno.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany("Turmas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_turmas_disciplinas_disciplina_id");

                    b.HasOne("Portal_Aluno.Domain.Entities.Professor", "Professor")
                        .WithMany("Turmas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_turmas_professores_professor_id");

                    b.HasOne("Portal_Aluno.Domain.Entities.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .HasConstraintName("fk_turmas_salas_sala_id");

                    b.Navigation("Curso");

                    b.Navigation("Disciplina");

                    b.Navigation("Professor");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Curso", b =>
                {
                    b.Navigation("CursoDisciplinas");

                    b.Navigation("Matriculas");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Disciplina", b =>
                {
                    b.Navigation("CursoDisciplinas");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Matricula", b =>
                {
                    b.Navigation("MatriculaTurmas");
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Professor", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("Portal_Aluno.Domain.Entities.Turma", b =>
                {
                    b.Navigation("MatriculaTurmas");
                });
#pragma warning restore 612, 618
        }
    }
}
